In [27]:
from pandas import read_csv
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN
from sklearn.preprocessing import MinMaxScaler
import math
import matplotlib.pyplot as plt

In [28]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set=pd.read_csv('Google_Stock_Price_Train.csv',index_col='Date',parse_dates=True)
training_set_scaled = sc.fit_transform(training_set)

In [29]:
Train=training_set_scaled[:1006]
Test=training_set_scaled[1006:]


In [30]:
from keras.preprocessing.sequence import TimeseriesGenerator

n_input = 3
n_features = 5
generator = TimeseriesGenerator(Train, Train, length=n_input, batch_size=1)
generatorTest=TimeseriesGenerator(Test,Test,length=n_input,batch_size=1)

In [31]:
X,Y=generator[1]

In [32]:
X

array([[[0.09701243, 0.09834351, 0.09823458, 0.24151427, 0.22993592],
        [0.09433366, 0.09251685, 0.09408623, 0.22878051, 0.26361233],
        [0.09156187, 0.08881917, 0.08800576, 0.21641884, 0.21617942]]])

In [33]:
Y

array([[0.07984225, 0.07671765, 0.06106986, 0.1785483 , 0.46779736]])

In [34]:
modelGoogle=Sequential()
modelGoogle.add(SimpleRNN(units=100, input_shape=(n_input,n_features),activation='tanh'))
modelGoogle.add(Dense(units=1,activation='tanh'))
modelGoogle.compile(loss='mean_squared_error', optimizer='adam')

In [35]:
modelGoogle.fit(generator, epochs=20)

Epoch 1/20
1003/1003 [==============================] - 2s 977us/step - loss: 0.0356
Epoch 2/20
1003/1003 [==============================] - 1s 981us/step - loss: 0.0345
Epoch 3/20
1003/1003 [==============================] - 1s 982us/step - loss: 0.0344
Epoch 4/20
1003/1003 [==============================] - 1s 1ms/step - loss: 0.0344
Epoch 5/20
1003/1003 [==============================] - 1s 997us/step - loss: 0.0343
Epoch 6/20
1003/1003 [==============================] - 1s 1ms/step - loss: 0.0343
Epoch 7/20
1003/1003 [==============================] - 1s 997us/step - loss: 0.0343
Epoch 8/20
1003/1003 [==============================] - 1s 996us/step - loss: 0.0343
Epoch 9/20
1003/1003 [==============================] - 1s 995us/step - loss: 0.0344
Epoch 10/20
1003/1003 [==============================] - 1s 994us/step - loss: 0.0343
Epoch 11/20
1003/1003 [==============================] - 1s 1ms/step - loss: 0.0343
Epoch 12/20
1003/1003 [==============================] - 1s 1ms/step 

In [21]:
Predictions=modelGoogle.predict(generatorTest)

249/249 [==============================] - 0s 714us/step


In [22]:
print("Actual--",generatorTest[40],"\t Predictions---",Predictions[40])

Actual-- (array([[[0.81829005, 0.81944834, 0.82357175, 0.31372738, 0.06492191],
        [0.81769477, 0.8184212 , 0.81224428, 0.30486612, 0.07809772],
        [0.81083042, 0.81289335, 0.81224428, 0.3027576 , 0.07866239]]]), array([[0.79578094, 0.79720619, 0.77602667, 0.28107989, 0.11923108]])) 	 Predictions--- [0.5635658]


In [23]:
Predictions[40]

array([0.5635658], dtype=float32)

In [26]:
generatorTest[40]

(array([[[0.81829005, 0.81944834, 0.82357175, 0.31372738, 0.06492191],
         [0.81769477, 0.8184212 , 0.81224428, 0.30486612, 0.07809772],
         [0.81083042, 0.81289335, 0.81224428, 0.3027576 , 0.07866239]]]),
 array([[0.79578094, 0.79720619, 0.77602667, 0.28107989, 0.11923108]]))