In [15]:
from pandas import read_csv
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, LSTM
from sklearn.preprocessing import MinMaxScaler
import math
import matplotlib.pyplot as plt

In [16]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set=pd.read_csv('NIFTY.csv',index_col='Date',parse_dates=True)
training_set_scaled = sc.fit_transform(training_set)

C:\Users\jinav\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '13-03-2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\jinav\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '16-03-2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\jinav\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '17-03-2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\jinav\anaconda3\lib\site-packages\pandas\io\parsers\base_parser.py:1070: UserWarning: Parsing '18-03-2009' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  return tools.to_datetime(
C:\Users\jinav\anaconda3\lib

In [24]:
Train=training_set_scaled[:1006]
Test=training_set_scaled[1006:]


In [25]:
from keras.preprocessing.sequence import TimeseriesGenerator

n_input = 30
n_features = 4
generator = TimeseriesGenerator(Train, Train, length=n_input, batch_size=1)
generatorTest=TimeseriesGenerator(Test,Test,length=n_input,batch_size=1)

In [26]:
X,Y=generator[0]

In [27]:
X

array([[[0.44754647, 0.42956052, 0.4862573 , 0.4472731 ],
        [0.4472731 , 0.43641819, 0.4826868 , 0.45711454],
        [0.45711454, 0.43628631, 0.4969688 , 0.43838846],
        [0.43838846, 0.42072467, 0.47093391, 0.42430973],
        [0.42430973, 0.40463552, 0.42868301, 0.37879306],
        [0.37879306, 0.40001978, 0.43746048, 0.41583516],
        [0.41583516, 0.39645907, 0.44251869, 0.39396528],
        [0.39396528, 0.37535854, 0.39163908, 0.34325451],
        [0.34325451, 0.35702746, 0.39878008, 0.3588368 ],
        [0.3588368 , 0.36863275, 0.38821735, 0.3824836 ],
        [0.3824836 , 0.36995153, 0.4200543 , 0.37865637],
        [0.37865637, 0.3665227 , 0.41499609, 0.37305221],
        [0.37305221, 0.35847812, 0.39015137, 0.3629374 ],
        [0.3629374 , 0.3665227 , 0.41454978, 0.38467059],
        [0.38467059, 0.38313936, 0.4103842 , 0.37687944],
        [0.37687944, 0.40740497, 0.40443337, 0.36854155],
        [0.36854155, 0.38762322, 0.41306207, 0.36608119],
        [0.366

In [28]:
Y

array([[0.60090897, 0.58267119, 0.61925838, 0.58532668]])

In [29]:
modelGoogle=Sequential()
modelGoogle.add(LSTM(units=100, input_shape=(n_input,n_features),activation='tanh'))
modelGoogle.add(Dense(units=1,activation='tanh'))
modelGoogle.compile(loss='mean_squared_error', optimizer='adam',metrics=['accuracy'])

In [ ]:
modelGoogle.fit(generator, epochs=20)

Epoch 1/20
760/976 [======================>.......] - ETA: 1s - loss: 9.8091e-04 - accuracy: 0.0000e+00

In [42]:
Predictions=modelGoogle.predict(generatorTest)

1760/1760 [==============================] - 1s 669us/step


In [43]:
print("Actual--",generatorTest[40],"\t Predictions---",Predictions[40])

Actual-- (array([[[0.09188764, 0.0969635 , 0.11581805, 0.10500957],
        [0.10500957, 0.10171112, 0.12950497, 0.09967879],
        [0.09967879, 0.09261152, 0.11909101, 0.09735511]]]), array([[0.09735511, 0.09472157, 0.12712463, 0.09926873]])) 	 Predictions--- [0.10265423]


In [44]:
Predictions[40]

array([0.10265423], dtype=float32)

In [45]:
generatorTest[40]

(array([[[0.09188764, 0.0969635 , 0.11581805, 0.10500957],
         [0.10500957, 0.10171112, 0.12950497, 0.09967879],
         [0.09967879, 0.09261152, 0.11909101, 0.09735511]]]),
 array([[0.09735511, 0.09472157, 0.12712463, 0.09926873]]))

In [11]:
from keras.layers import LSTM
# define model
modelLSTM = Sequential()
modelLSTM.add(LSTM(100, activation='relu', input_shape=(n_input, n_features)))
modelLSTM.add(Dense(1))
modelLSTM.compile(optimizer='adam', loss='mse')

In [12]:
modelLSTM.fit(generator, epochs=20)

Epoch 1/20
1003/1003 [==============================] - 2s 1ms/step - loss: 0.0014
Epoch 2/20
1003/1003 [==============================] - 1s 1ms/step - loss: 6.7705e-04
Epoch 3/20
1003/1003 [==============================] - 1s 1ms/step - loss: 6.1863e-04
Epoch 4/20
1003/1003 [==============================] - 1s 1ms/step - loss: 5.5727e-04
Epoch 5/20
1003/1003 [==============================] - 2s 2ms/step - loss: 4.9242e-04
Epoch 6/20
1003/1003 [==============================] - 1s 1ms/step - loss: 4.4945e-04
Epoch 7/20
1003/1003 [==============================] - 2s 2ms/step - loss: 4.4237e-04
Epoch 8/20
1003/1003 [==============================] - 1s 1ms/step - loss: 4.4326e-04
Epoch 9/20
1003/1003 [==============================] - 1s 1ms/step - loss: 4.5617e-04
Epoch 10/20
1003/1003 [==============================] - 2s 2ms/step - loss: 4.2143e-04
Epoch 11/20
1003/1003 [==============================] - 1s 1ms/step - loss: 4.1557e-04
Epoch 12/20
1003/1003 [======================